---
- name: create zookeeper data directory
  become: yes
  file: path=/data/zookeeper state=directory mode=0755

- name: ensure zookeeper container is running
  become: yes
  docker:
    name: zookeeper
    image: ah45/zookeeper
    pull: always
    state: started
    restart_policy: on-failure
    restart_policy_retry: 10
    hostname: "{{ ansible_hostname }}.node.dc1.consul.{{ ansible_domain }}"
    volumes:
      - /data/zookeeper:/data
    ports:
      - 2172:2172
      - 2173:2173
      - 2181:2181
      - "{{ ansible_default_ipv4.address }}::8080"
    env:
      ID: 1
      QUORUM: "{% for host in groups['zookeeper'] if not host == ansible_nodename %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2181 {% endfor %}"
