---
- hosts: all
  tasks:
  - name: Ensure .ssh dir exists
    file: >
      path="/home/{{ ansible_user_id }}/.ssh"
      mode=0700 owner="{{ ansible_user_id }}"
      state=directory
  - name: Replace authorized keys
    template: >
      src="templates/authorized_keys.j2"
      dest="/home/{{ ansible_user_id }}/.ssh/authorized_keys"
      mode=0600
      owner="{{ ansible_user_id }}"
