---
- hosts: all
  tasks:
  - name: Set new random root password
    become: yes
    user: name=root password="{{ lookup('password', '/tmp/ansibleremoterootpwd length=30') | password_hash('sha512') }}"

- include: authorized_keys.yml
