---
- hosts: consul
  roles:
    - consul-server
    - registrator

- hosts: all
  roles:
    - consul-agent
    - registrator

- hosts: zookeeper
  roles:
    - zookeeper

- hosts: kafka
  roles:
    - kafka
